version: "3.3"
services:
  letsencrypt:
    container_name: 'certbot-service'
    image: certbot/certbot:v1.17.0
    command: sh -c "certbot certonly --webroot -w /tmp/acme_challenge -d ${DOMAIN:-roshamagin.site} -d www.${DOMAIN:-roshamagin.site} --text --agree-tos --email admin@${DOMAIN:-roshamagin.site} --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/tmp/acme_challenge:/tmp/acme_challenge"
    environment:
      - TERM: xterm
      - DOMAIN: roshamagin.site